### ISSUE TITLE
Server generates recent changes page

### ISSUE THREAD

**Issue by opn** [fedwiki/wiki-node-server#100]
Taking a look at server - I see that it generates the [[Recent Pages]] json in response to a request from the client.

It would seem to me that all the necessary information is already available to the client to generate a Recent Pages page from the site map JSON - so the request is unnecessary? To check whether client and server are in sink we'd need to just check the sitemaps - not have the server render this page?

**Comment by paul90** [comment]
The server serves up a recent-changes.json page - this contains an [*activity* item](https://github.com/fedwiki/wiki-plugin-activity/blob/master/pages/recent-changes#L10).

The server does not render the contents of the activity plugin, this is done on the client using the code loaded from the activity plugin (using the sitemap data).
