### ISSUE TITLE
Stealth Persona Disabling in Farm Mode

### ISSUE THREAD

**Issue by opn** [fedwiki/wiki-node-server#102]
Following @WardCunningham observation that if you don't claim a site, it will let you post anything. I started as instructed to "Think of not-claiming as disabling-persona". This made me feel good and warm inside.

This feature enables offline running of a wiki-farm setup on a laptop. This is useful. I tried @paul90 's suggestion of running the wiki farm on localhost and not claiming sites with interesting results.

Rather than the farm creating sites based on the referer's IP address - it creates a site based on it's own address, which results in several people editing the same wiki. I guess this is a bug with a simple fix?

In a future and better world I dream of an authentication plugin architecture which plays well with WebID and the ongoing WC3 specs in this area - something to hack on at Chaos Camp?

**Comment by paul90** [comment]
I said it will name the site using the name used to access the site. 

If you're using the IP address to access the site, the IP address will get used to name the wiki. Thought you were using zero config networking to give the server multiple names...

**Comment by WardCunningham** [comment]
The federation could get along without using dns and only sharing ip addresses among friends. I have suggested that site operators claim the farm site named after their server's ip address. I call this "nameless" networking. See http://128.199.166.158/nameless-wiki.html

This hasn't caught on yet.

**Comment by opn** [comment]
Maybe I was not clear. It is not a question of name-vs-ip address. The server is taking it's IP address to create a site instead of the remote wiki-clients ip address). 

I will test this with zero-conf names. But the wiki-server should choose the remote sits IP not it's own when creating the site?

**Comment by paul90** [comment]
> The server is taking it's IP address to create a site instead of the remote wiki-clients ip address

That would never work. If you were on IP address 10.11.12.13 a request to create a wiki with that name would go to your machine - my server would never see the request. And if you accessed my server, and we used your client address to route to the wiki, then that wiki would only be visible to you, or whoever gets that IP address in the future.
